language: ruby
bundler_args: --without development
rvm:
  - 1.9.2
  - 1.9.3
  - jruby-19mode
  - rbx-19mode
matrix:
  allow_failures:
    - rvm:  1.9.2
    - rvm:  rbx-19mode
    - rvm:  jruby-19mode
